# ========== Keyboard Path ========== #

keyboard_input_path: /dev/input/event7

# ========== Keybinds config ========== #

activation_key: HOME
activate_division_overlay_key: M
mouse_click: SPACE
mouse_right_click: Q
mouse_up: W
mouse_left: A
mouse_down: S
mouse_right: D
scroll_up: K
scroll_left: H
scroll_down: J
scroll_right: L

# ========== Movement modifier config ========== #

mouse_speed: 10
scroll_speed: 1

# ========== overlay config ========== #

screen_x_resolution: 1920
screen_y_resolution: 1080

number_of_divisions: 2
division_dimensions:
  - [16, 10]
  - [5, 5]

division_navigators: 
  - [
    AR, AT, AY, AP, AS, AD, AF, AG, AH, AJ, AK, AL, AC, AV, AN, AM,
    RA, TA, YA, PA, SA, DA, FA, GA, HA, JA, KA, LA, CA, VA, NA, MA,
    EQ, EW, ER, ET, EY, EP, ES, EF, EG, EH, EJ, EK, EL, EB, EN, EM,
    QE, WE, RE, TE, YE, PE, SE, FE, GE, HE, JE, KE, LE, BE, NE, ME,
    IQ, IW, IT, IP, IA, IS, ID, IF, IG, IH, IJ, IL, IC, IV, IN, IM,
    QI, WI, TI, PI, AI, SI, DI, FI, GI, HI, JI, LI, CI, VI, NI, MI,
    OW, OR, OT, OP, OS, OD, OF, OG, OH, OJ, OK, OC, OV, OB, "ON", OM,
    WO, RO, TO, PO, SO, DO, FO, GO, HO, JO, KO, CO, VO, BO, "NO", MO,
    UQ, UW, UR, UT, UP, US, UD, UF, UG, UH, UK, UL, UC, UV, UN, UM,
    QU, WU, RU, TU, PU, SU, DU, FU, GU, HU, KU, LU, CU, VU, NU, MU,
  ]
  - [
    Q, W, E, R, T, 
    Y, U, I, O, P,
    A, S, D, F, G,
    H, J, K, L, X,
    C, V, B, N, M,
  ]

click_after_select: TRUE
mouse_mode_after_select: FALSE

# ========== Overlay visuals ========== #

overlay_rgba: [0, 0, 0, 0.3]
division_lines_rgba: [255, 255, 255, 0.3]
division_navigators_rgba: [255, 255, 255, 0.8]
font_size_multiplier: 0.1
