# ========== Keyboard Path ========== #

keyboard_input_path: /dev/input/event7

# ========== Keybinds config ========== #

activation_key: HOME
activate_division_overlay_key: M
mouse_click: SPACE
mouse_up: W
mouse_left: A
mouse_down: S
mouse_right: D
scroll_up: K
scroll_left: H
scroll_down: J
scroll_right: L

# ========== Movement modifier config ========== #

mouse_speed: 10
scroll_speed: 1

# ========== overlay config ========== #

screen_x_resolution: 1920
screen_y_resolution: 1080

number_of_divisions: 2
division_dimensions:
  - [20, 5]
  - [4, 6]
division_navigators: 
  - [AE, AR, AT, AY, AU, AI, AP, AS, AD, AF, AG, AH, AJ, AK, AL, AC, AV, AB, AN, AM,
    EQ, EW, ER, ET, EY, EU, EI, EP, EA, ES, EF, EG, EH, EJ, EK, EL, EC, EV, EN, EM,
    IQ, IW, IE, IR, IT, IU, IO, IP, IA, IS, ID, IF, IG, IH, IJ, IL, IC, IV, IN, IM,
    OQ, OW, OE, OR, OT, OU, OI, OP, OA, OS, OD, OF, OG, OH, OJ, OK, OC, OV, "ON", OM,
    UQ, UW, UE, UR, UT, UI, UO, UP, UA, US, UD, UF, UG, UH, UL, UC, UV, UB, UN, UM]
  - [Q, W, E, R, T, Y, U, I, O, P, A, S, D, F, G, H, J, K, L, C, V, B, N, M]

click_after_select: TRUE
mouse_mode_after_select: FALSE

# ========== Overlay visuals ========== #

overlay_rgba: [0, 0, 0, 0.3]
division_lines_rgba: [255, 255, 255, 0.3]
division_navigators_rgba: [255, 255, 255, 0.8]


