# ========== Keyboard Path ========== #

keyboard_input_path: /dev/input/event7

# ========== Keybinds config ========== #

activation_key: HOME
activate_division_overlay_key: M
mouse_click: SPACE
mouse_up: W
mouse_left: A
mouse_down: S
mouse_right: D
scroll_up: K
scroll_left: H
scroll_down: J
scroll_right: L

# ========== Movement modifier config ========== #

mouse_speed: 10
scroll_speed: 1

# ========== overlay config ========== #

screen_x_resolution: 1920
screen_y_resolution: 1080

number_of_divisions: 3
division_dimensions:
  - [3, 2]
  - [3, 2]
  - [3, 2]
division_navigators: 
  - [A, S, D, F, J, K]
  - [A, S, D, F, J, K]
  - [A, S, D, F, J, K]
